spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mqs-sensors
          uri: lb://measurement-query-service
          predicates:
            - Path=/api/v1/sensors/**
        - id: mqs-locations
          uri: lb://measurement-query-service
          predicates:
            - Path=/api/v1/locations/**
        - id: mqs-rooms
          uri: lb://measurement-query-service
          predicates:
            - Path=/api/v1/rooms/**

server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info