spring:
  application:
    name: measurement-storage-service
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  exchange:
    name: sensor.exchange
  queue:
    name: sensor.queue
  routing:
    measurement: sensor.tracking
    availability: sensor.availability

server:
  port: 8083

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5