spring:
  application:
    name: measurement-query-service
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-db
    username: measurement
    password: pass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

server:
  port: 8084