spring:
  application:
    name: mqtt-ingest-service
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

rabbitmq:
  exchange:
    name: sensor.exchange
  queue:
    name: sensor.queue
  routing:
    measurement: sensor.tracking
    availability: sensor.availability

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

server:
  port: 8083